# Generated by Django 4.2.6 on 2023-10-17 03:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CupomDesconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=8, unique=True)),
                ("desconto", models.FloatField()),
                ("usos", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=200)),
                ("total", models.FloatField()),
                ("troco", models.CharField(blank=True, max_length=20)),
                ("pagamento", models.CharField(max_length=20)),
                ("ponto_referencia", models.CharField(blank=True, max_length=2000)),
                (
                    "data",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 10, 17, 3, 40, 1, 50100)
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=50)),
                ("rua", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=10)),
                ("bairro", models.CharField(blank=True, max_length=200)),
                ("telefone", models.CharField(max_length=30)),
                ("entregue", models.BooleanField(default=False)),
                (
                    "cupom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedido.cupomdesconto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("preco", models.FloatField()),
                ("descricao", models.TextField()),
                ("adicionais", models.TextField()),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pedido.pedido"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produto",
                    ),
                ),
            ],
        ),
    ]
