# Generated by Django 4.2.6 on 2023-10-17 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 17, 3, 41, 53, 979626)
            ),
        ),
    ]
